### ISSUE TITLE
additionalProperties doesn't serialize properly

### ISSUE THREAD

**Issue by hmil** [qri-io/jsonschema#117]
The keyword `additionalProperties` always serializes to the empty schema `{}` regardless of what it is actually set to.

I believe the following code is missing from `keywords_object.go`, but I'm a go newbie so I'm not sure...

```go
// MarshalJSON implements the json.Marshaler interface for AdditionalProperties
func (ap AdditionalProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(Schema(ap))
}
```

**Comment by Arqu** [comment]
should be covered now by https://github.com/qri-io/jsonschema/pull/123
