### ISSUE TITLE
Are there plans to support draft 2020-12?

### ISSUE THREAD

**Issue by insano10** [qri-io/jsonschema#121]
Just curious and wondered what the appetite is to keep up to date with the latest version.

**Comment by handrews** [comment]
Note that with the _next_ version (hopefully out in early 2023) JSON Schema will be moving to a new model of marking features and keywords stable vs unstable so there won't be a need to keep publishing totally distinct "drafts" that have to be supported separately.  There will be a [blog post](https://json-schema.org/blog) soon or you can read the longer [discussion](https://github.com/json-schema-org/community/discussions/234) now.

**Comment by insano10** [comment]
Ah interesting. Thanks for the info 👍

**Comment by handrews** [comment]
Blog post just went up: https://json-schema.org/blog/posts/future-of-json-schema

**Comment by insano10** [comment]
Ah fab. The new system sounds good. I dislike upgrading libraries out of fear of becoming obsolete. Thanks for sharing ♥
