### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by ion2014** [qri-io/jsonschema#128]
Hi

I've encountered the default and additionalProperties marshall failures and there's PR fixing the issue being out for +1 year. 
If this repo isn't maintained anymore, are there any recommended alternatives out there? ty

**Comment by Arqu** [comment]
Hi, sorry about that, but life pulls you into different directions and I didn't really have much time for side projects. Still, could have been a little bit more prompt. 

The main issue here is that the draft got pretty out of date by now and would require quite a bit of work to bring up to speed again. IIRC there were a number of different implementations at the time of writing this, each with it's own edge cases and perf characteristics.

**Comment by Arqu** [comment]
I've done a quick pass to get the additionalProperties merged, hope this helps.
