### ISSUE TITLE
jsonschema needs a method to report *all* errors in an instance

### ISSUE THREAD

**Issue by b5** [qri-io/jsonschema#15]
currently we only have one usable Method for Validation:
```go
jsonschema.RootSchema.ValidateBytes(data []byte) error
```
That bails on the first error it sees.

We need a method that collects _all_ known errors in a slice of bytes. I'm thinking it's signature should look like this:
```go
jsonschema.RootSchema.Errors(data []byte) ([]string, error)
```
the slice of string should be the result of appending `err.Error()` to the result anytime `err != nil` in the validation stack. the function should only return `error != nil` if the data won't parse.

**Comment by handrews** [comment]
You may be interested in json-schema-org/json-schema-spec#396 related to this, about a possible suggested error output format.
