### ISSUE TITLE
$id begning with `#` causes panic

### ISSUE THREAD

**Issue by daveamit** [qri-io/jsonschema#38]
Hi,
  We use `https://www.jsonschema.net/` as an interactive tool to generate JSON schemas, its very productive especially for non technical team members.

One of our team members configured the system to use following schema:
```
{
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/root.json",
    "type": "object",
    "title": "The Root Schema",
    "required": [
      "firstName",
      "lastName",
      "username"
    ],
    "properties": {
      "firstName": {
        "$id": "#/properties/firstName",
        "type": "string",
        "title": "The Firstname Schema",
        "default": "",
        "examples": [
          "Amit"
        ],
        "minLength": 2,
        "pattern": "^(.*)$"
      },
      "lastName": {
        "$id": "#/properties/lastName",
        "type": "string",
        "title": "The Lastname Schema",
        "default": "",
        "examples": [
          "Dave"
        ],
        "pattern": "^(.*)$"
      },
      "avatar": {
        "$id": "#/properties/avatar",
        "type": "string",
        "title": "The profile picture",
        "description": "The picture is used at multiple places in the frontend",
        "default": "",
        "examples": [
          "https://lh3.googleusercontent.com/-bI-uHAaXyKk/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rdOVryMbEIxiHnO81R8gvWjJeQ33A/s32-c-mo/photo.jpg"
        ],
        "pattern": "^(.*)$",
        "format": "uri"
      },
      "username": {
        "$id": "#/properties/username",
        "type": "string",
        "title": "The Username Schema",
        "default": "",
        "examples": [
          "root"
        ],
        "pattern": "^(.*)$"
      }
    }
  }
```

Everything seems okay with it, but still when the system tried to `Unmarshal` above mentioned schema to `RootSchema` program would exit with a panic `panic: runtime error: slice bounds out of range`.

So I started investigating the issue and I found that following was causing the issue

[link to code](https://github.com/qri-io/jsonschema/blob/master/schema.go#L93)
```
				// For the record, I think this is rediculous.
				if u, err := url.Parse(sch.ID); err == nil {
					ids[u.Path[1:]] = sch
				}
```

especially the line `ids[u.Path[1:]] = sch`. Though `url.Parse` is able to parse relative paths without `hostname` and `protocol`, if the relative path started with `#`, i.e. `#/properties/firstName`, the desired path will be present in `Fragment` and `Path` will be `empty` hence while trying to slice an empty path from `1:` causes the panic.

I was able to resolve this by replacing above code with following:
```
				// For the record, I think this is ridiculous.
				if u, err := url.Parse(sch.ID); err == nil {
					// This is if the identifier is defined as a reference (with #)
					// i.e. #/properties/firstName
					// in this case, u.Fragment will have /properties/firstName
					if strings.HasPrefix(sch.ID, "#") {
						ids[u.Fragment[1:]] = sch
					} else {
						ids[u.Path[1:]] = sch
					}
				}
```
This fix is already present in my clone [here](https://github.com/daveamit/jsonschema/blob/master/schema.go#L98)

If you feel that this fix is an appropriate fix, I'd be more then happy to submit a PR. If not, please provide some feedback.

Thanks.

PS: Love this lib for its simplicity.

**Comment by b5** [comment]
Thanks so much for your PR @daveamit, and for the clear feedback in this issue. Now that your PR is merged, would you mind checking if this fixes the issue your team member was facing, and if so close this issue?

**Comment by daveamit** [comment]
@b5 thanks for accepting the PR, I can confirm that the issue my team was facing has been resolved.
