### ISSUE TITLE
custom msg errors

### ISSUE THREAD

**Issue by msAlcantara** [qri-io/jsonschema#41]
Exist a way of customized message errors when validation fails? If not maybe should be useful to do that

**Comment by Arqu** [comment]
I'd like to keep the implementation separate from user side logic. As such I think it should be fairly easy for someone to provide their own error handling/responses by utilizing the output returned from the validation. Specifically the `KeyError` structure and the `PropertyPath` which should indicate the location of the error and help you present a message you want to the user.
