### ISSUE TITLE
[Request] Populate with default values

### ISSUE THREAD

**Issue by olegsu** [qri-io/jsonschema#58]
Hey, 
I'm trying to validate objects against my schema.
In my case, the JSON schema has some default values of part of the properties, in case the given object does not include them, so I forced to manually iterate over the object and fill those defaults.
Any chance to have it as part of the validation? 
A similar project I'm using in my Nodejs app [ajv](https://github.com/jessedc/ajv-cli#ajv-options)
I think that with your help I can do most of the job, what do you think?

**Comment by b5** [comment]
:wave: @olegsu,

Totally agreed we should have this as a default, and provide optional configuration to disable it. I'm a little too busy at the moment to take this on, but I'm planning to revisit this package in early November, and should be able to get default value setting in then.

If you're interested in submitting a PR, we'd be happy to work with you on it!

**Comment by olegsu** [comment]
@Thanks @b5 
Unfortunately, I also will not be able to submit a PR this month as well.
I will be back on the 3rd of November to work on it.

**Comment by handrews** [comment]
@b5 If your validator inserts `default` values into the instance by default and requires users to turn off that functionality, then it will be out of compliance with the spec.  It's fine to offer it as an opt-in behavior (which I think is what ajv does), but it's incorrect to make it opt-out.

**Comment by b5** [comment]
Ah very good point, thanks @handrews! @olegsu we'll have to make it opt-in (we aim to be a proper implementation of the spec).

**Comment by stremovsky** [comment]
Hi

Any updates on this topic?

**Comment by Arqu** [comment]
Not really an update but some input on the topic if someone is interested in picking this up in the meantime or as a temporary workaround.

Currently we don't have a propper way to "configure" the validator with anything but whatever the default behavior is. To start supporting these "outside of spec" behaviors (which I'm not super keen about but would like some of these QoL changes in there) we need to implement some config mechanism for the Schema/Validation.

Other than that, what this usecase needs is a modified implementation of the "Default" keyword.

My recommended approach would be to simply configure the validator by loading your own key spec. See `draft2019_09_keywords.go` for a list of current keywords. These are automatically loaded in no other keywoard was defined prior to validation. In this case we just need to implement a custom keyword with the desired behavior (overwrite value if empty) and load it under the "default" keyword (along with the others) prior to the first validation.

This also allows you to control what you consider empty and when to load the default and when not to.

**Comment by studiogangster** [comment]
Is this implemented.in the latest release ? If not, when can we expect this ?

**Comment by Arqu** [comment]
@studiogangster as per the discussion above, this is a bit out of spec and won't be implemented directly for now. But you can roll your own version as outlined in my last comment. 

As we don't have any timeline on this and there are much higher priority issues, I'll close this out and maintain the option for users to implement their own version of the `default` behavior.
