### ISSUE TITLE
RootSchema: pass interface{} as schema and validate interface{}

### ISSUE THREAD

**Issue by epoberezkin** [qri-io/jsonschema#60]
To set schema from interface{} (in addition to UnmarshalJSON)
To validate data from interface{} (in addition to ValidateBytes)
Is it ok to add these APIs? Not sure what would be the best names for the methods, happy to make PR

**Comment by MaikuMori** [comment]
What's the advantage over just converting to JSON or bytes and then calling the functions?

**Comment by epoberezkin** [comment]
To avoid extra serialisation and deserialisation when schema and data already deserialised. Available functions deserialise under the hood, I have to serialise the schema and data to pass them in - I am just using Schema for validation (which is a bit ugly) and there is no equivalent API to initialise the schema.

**Comment by epoberezkin** [comment]
In my case schema is deserialised because it is generated with code. Data is deserialised to avoid extra deserialisation after validation.

**Comment by MaikuMori** [comment]
I see.

For extra context this is how I use this package:
I have a list of schemas which are JSON files which get loaded with the app. At the same time I use those JSON schema files to generate go structures. Then incoming data is being validated against the schema and on success unmarshalled. 

It does seem like those extra functions could be useful.

**Comment by dolmen** [comment]
Related to #53 which also asks to extended the input source.

**Comment by dolmen** [comment]
Isn't [`Schema.Validate`](https://pkg.go.dev/github.com/qri-io/jsonschema?tab=doc#Schema.Validate) what you want?

**Comment by Arqu** [comment]
I might be getting this wrong, but assuming my understanding is correct, you want to be able to validate arbitrary go structures against the schema. While definitely interesting, it's an interesting bit of work as some of the internals rely on some json specific conversions and behavior. As such the bridge would be to have those structures implement the json marshaller interfaces but then that would mean you can simply pass them in without having to do anything against the current implementation. 

Agree that a bit extra efficiency could be squeezed in the ideal case as we avoid unnecessary serialization/deserialization however that opens jsonschema to a much wider surface for "unplanned" usage of the lib which would be a bit harder to support long term.

Also, this applies more to the older version and the current iteration might be closer to what you expect.

I'll close for now, if this is still an issue, happy to reopen.
