### ISSUE TITLE
enum validation failure

### ISSUE THREAD

**Issue by bradleyjames** [qri-io/jsonschema#61]
I'm trying to use the `enum` example in [Understanding JSON Schema](https://json-schema.org/understanding-json-schema/reference/generic.html#enumerated-values).  Using https://www.jsonschemavalidator.net the example behaves as documented in the example.

Below is my test which should fail but doesn't.  It fails if I pass an int so I know it's being evaluated.

```golang
func TestVersion_test(t *testing.T) {
	schema := []byte(`
{
  "type": "string",
  "enum": ["red", "amber", "green"]
}
	`)
	root := &jsonschema.RootSchema{}

	if err := json.Unmarshal(schema, root); err != nil {
		t.Fatalf("Unmarshaling schema: %v\n", err)
	}
	valid := []byte(`blue`)

	if errors, _ := root.ValidateBytes(valid); len(errors) > 0 {
		t.Fatalf("Validation failures: %v\n", errors)
	}
}
```

My library version is `github.com/qri-io/jsonschema v0.1.1`.

**Comment by Arqu** [comment]
Thanks for reporting this. Wanted to let you know a rewrite is in progress that will cover this.

**Comment by Arqu** [comment]
This should now work as expected.
