### ISSUE TITLE
Implement Draft 7 optional validators

### ISSUE THREAD

**Issue by b5** [qri-io/jsonschema#7]
There are optional validators currently not implemented, let's get 'em written!

Optional Validators that need writing for this issue:
* [ ] `bignum`
* [ ] `content`
* [ ] `ecmascript-regex`
* [x] `zeroTerminatedFloats`

Steps to complete:
* [ ] open a WIP PR so others know what you're up to, be sure to follow contribution guidelines (#6 ) while working to make for easier merging later
* [ ] uncomment the corresponding .json file in `TestDraft7` for each data type
* [ ] add a new file `keywords_optional.go`, write new definitions for each of these optional types, being sure to implement interfaces when necessary
* [ ] add tests for these optional types to `TestReferenceTraversal`, making sure traversal for these new types work, especially when references are involved/applicable
* [ ] get tests to pass
* [ ] request review on PR, get it merged, 🚀

**Comment by osterbit** [comment]
@b5 in order to handle zero-terminated floats, I think we need to intervene before [this switch](https://github.com/qri-io/jsonschema/blob/master/keywords.go#L24) (in `func DataType()`, line 24 of keywords.go) to note the byte length and then compare it length (and/or presence of a '.', 'e') of a string representation of the number (if it is a number).  thoughts?

**Comment by osterbit** [comment]
had misinterpreted the zero-terminated floats validation.  the test according to the spec is 
```json
[
    {
        "description": "some languages do not distinguish between different types of numeric value",
        "schema": {
            "type": "integer"
        },
        "tests": [
            {
                "description": "a float without fractional part is an integer",
                "data": 1.0,
                "valid": true
            }
        ]
    }
]

```
so the current logic in `func Datatype()` 
```go
	case float64:
		if float64(int(v)) == v {
			return "integer"
		}
```
should satisfy this

**Comment by osterbit** [comment]
*Note this is the correct interpretation for drafts 6 and later but earlier drafts specify the opposite: 42.0 should be parsed as a float not an int

**Comment by osterbit** [comment]
- zeroTerminatedFloats is taken care of
- bignum moved to #16 
- content moved to #18 
- ecmascript-regex moved to #19
