### ISSUE TITLE
Question: jsonpointer Eval?

### ISSUE THREAD

**Issue by benpate** [qri-io/jsonschema#70]
I'm getting started with this jsonschema -- great work, QRI.IO.

In my project, I have a `jsonschema.Schema` that has already been unmarshalled into an object, and want to use a `jsonpointer.Pointer` (or something like it) to reference a specific object property within it.  The jsonpointer library supports this for other kinds of objects, but I don't see this support when I'm using a Schema object.  This may already be available in the jsonschema library, somehow, but I'm having a tough time finding it.   

If this is available, but I've missed it in the documentation, then this ticket is requesting a clearer example of how to use it.

If this is NOT available, then this is a feature request to add it.  I'm happy to write this code and make a pull request, but it would help to have some guidance from the original developers, first.

The function signature would look something like

```
func (schema *Schema) EvalPointer(pointer jsonpointer.Pointer) (interface{}, error)
```

**Comment by dolmen** [comment]
Isn't [`Resolve`](https://pkg.go.dev/github.com/qri-io/jsonschema?tab=doc#Schema.Resolve) what you are looking for?

**Comment by benpate** [comment]
Very possibly.  Thanks for the pointer :) I think I was confused by the additional URI argument.  I'll dig deeper and see how it works for my use cases.
