### ISSUE TITLE
Provide access to original error from json.Unmarshal

### ISSUE THREAD

**Issue by aakhan1** [qri-io/jsonschema#83]
### What feature or capability would you like?
I would like to gain access the Offset property when a json syntax error occurs so I can report the line and column of the error.
```
schemaErrors, err := rs.ValidateBytes(ctx, document)
if err!=nil {
	syntaxError := err.(*json.SyntaxError)
	fmt.Println("The offset is:", syntaxError.Offset)
}
```
Unfortunately, this results in a panic because the `rs.ValidateBytes` returns a *errors.errorString
`panic: interface conversion: error is *errors.errorString, not *json.SyntaxError`

### Do you have a proposed solution?
Would it be possible to change the implementation of rs.ValidateBytes to return the error as a wrapped error?

Change the %s to %w?  Then I can unwrap the error and get what I need.
```
func (s *Schema) ValidateBytes(ctx context.Context, data []byte) ([]KeyError, error) {
	var doc interface{}
	if err := json.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("error parsing JSON bytes: %w", err) // <--- change from %s to %w
	}
	vs := s.Validate(ctx, doc)
	return *vs.Errs, nil
}
```
Or provide a method on the error object where the original error can be accessed.

### Have you considered any alternative solutions or workarounds?
I have implemented my own json.Unmarshal call before calling rs.ValidateBytes, but I feel this adds a performance delay unnecessarily.

**Comment by aakhan1** [comment]
@Arqu  I'd like to work on this if possible.

**Comment by Arqu** [comment]
@aakhan1 Absolutely appreciated, as you see time is tight, and help like this really polishes some of the rough edges. A PR is more than welcome. Happy hacktober :)

**Comment by Arqu** [comment]
Done in https://github.com/qri-io/jsonschema/pull/85
