### ISSUE TITLE
Required properties error path does not contain the required property name

### ISSUE THREAD

**Issue by asaf** [qri-io/jsonschema#91]
Hey,

Having a JSON schema with `required` properties generates an error such:

```
PropertyPath: "/"
Message: 'X value is required'
```

I understand that the error is actually on the object level but losing the context of the X field makes it very difficult to display the error under the 'X' field.

Does it make sense to keep the [property key](https://github.com/qri-io/jsonschema/blob/master/keywords_object.go#L105) that is required in the error somehow?

Thanks,
Asaf

**Comment by aakhan1** [comment]
Hi @asaf.  I reported a similar issue on this #81.  I tend to agree.  The property name that is the source of the exception should be made available.  I created my own version for the time being until this gets addressed.

**Comment by carolynvs** [comment]
I am confused by what the desired behavior is as well. On v0.1.1, the ProperyPath was set to the child that violated the schema. After upgrading to v0.2.0, the path is now set to the parent. I'm seeing this for both required and additionalProperties.

I'm not sure if this change was intended or if a fix (I only had to move a single line of code) would be welcome?

**Comment by peterhellberg** [comment]
I just noticed this issue as well (and that there hasn’t been a tagged release in quite some time).

It would be good if the behavior was documented if working as intended.

**Comment by Arqu** [comment]
I'll aim to review the spec and look into it by the end of the week if time permits to move this along.

**Comment by asaf** [comment]
@Arqu any news on this? thanks!

**Comment by Arqu** [comment]
I've looked into it and apparently neither is really up to spec anymore. As the output format is not really correct per spec.
Taking the more useful route, I'd say the better way would be to show the property path and not just the parent path until this is patched.

For anyone interested, the KeyError structure needs to be updated (and surrounding logic) to contain (at a minimum) `keywordLocation`, `instanceLocation` & `error` which would contain both options and satisfy the basic output format per spec.
